name: Build container images

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: latest_tag
        run: ::set-output name=GIT_LATEST_TAG::$(git describe --tags --abbrev=0)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push chaostoolkit-basic
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: chaostoolkit/chaostoolkit:basic
          file: ./container/Dockerfile-basic
          labels: |
            CTK_VERSION=${steps.latest_tag.outputs.GIT_LATEST_TAG}
            org.opencontainers.image.revision=${GITHUB_SHA}
      - name: Build and push chaostoolkit-full
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: chaostoolkit/chaostoolkit:full
          file: ./container/Dockerfile-full
          labels: |
            CTK_VERSION=${steps.latest_tag.outputs.GIT_LATEST_TAG}
            org.opencontainers.image.revision=${GITHUB_SHA}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}
          repository: chaostoolkit/chaostoolkit
          short-description: ${{ github.event.repository.description }}